version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: dev
    ports:
      - '4200:4200'
    environment:
      - HOST=0.0.0.0
    volumes:
      - ~/.gitconfig:/etc/gitconfig
      - ./src:/usr/src/app/src:cached
      - ./e2e:/usr/src/app/e2e:cached
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./tslint.json:/usr/src/app/tslint.json
      - ./package.json:/usr/src/app/package.json
    entrypoint: ng serve --host 0.0.0.0 --poll 1
